<?php
/**
 * @file
 * Code for the Govi eventos feature.
 */

include_once 'govi_eventos.features.inc';


/**
 * Implements hook_theme_registry_alter().
 * Trata al modulo como fuente de archivos de template para la caracteristica funcional. 
 */

function govi_eventos_theme_registry_alter(&$registry) {

  //agregamos la ruta donde esta almacenado los .tpl
  $path = drupal_get_path('module', 'govi_eventos') . '/templates';
  
  //identifica los archivos .tpl
  $templates = drupal_find_theme_templates($registry, '.tpl.php', $path);
 
  foreach ($templates as $key => $value) {
    $templates[$key]['type'] = 'module';
  }
  
  $registry += $templates;
}
