<?php

define('CUSTOM_WIDGETS_MODULE_PATH',drupal_get_path('module', 'custom_widgets'));

// Incluye la definición de los widgets extra
include_once(CUSTOM_WIDGETS_MODULE_PATH . '/includes/custom_widgets.extra.inc');


function easy_social_menu_alter(&$items) {

    $items['admin/config/content/easy_social/connect'] = array(
        'title' => 'API Settings',
        'description' => 'Configura la conexión con las API de redes sociales',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('custom_widgets_easy_social_admin_config_api'),
        'access arguments' => array('administer easy social'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 1,
        'file path' => CUSTOM_WIDGETS_MODULE_PATH,
        'file' => 'includes/custom_widgets.admin.inc',
    );

    return $items;
}

/**
 * Declara variables para ser reusadas en el scope del modulo
 *
 * Implementa hook_variable_info()
 */

function custom_widgets_variable_info() {
  $variables = array();

  // Variables de la seccion de configuración de la API 
  // Opengraph de facebook
  $variables['easy_social_global_fb_enabled'] = array(
    'title' => t('Usar Facebook SDK'),
    'default' => '',
    'group' => 'easy_social',
    'token' => FALSE,
  );

  $variables['easy_social_global_fb_appid'] = array(
    'title' => t('Facebook Application ID'),
    'default' => '',
    'group' => 'easy_social',
    'token' => FALSE,  
  );

  $variables['easy_social_global_fb_status'] = array(
    'title' => t('Facebook Application ID'),
    'default' => '',
    'group' => 'easy_social',
    'token' => FALSE,  
  );

  $variables['easy_social_global_fb_cookie'] = array(
    'title' => t('Facebook Cookie'),
    'default' => '',
    'group' => 'easy_social',
    'token' => FALSE,  
  );

  $variables['easy_social_global_fb_xfbml'] = array(
    'title' => t('Facebook xfbml'),
    'default' => '',
    'group' => 'easy_social',
    'token' => FALSE,  
  );

  $variables['easy_social_global_fb_version'] = array(
    'title' => t('Facebook version'),
    'default' => '',
    'group' => 'easy_social',
    'token' => FALSE,  
  );

  // Variables de los Widgets Custom Extra
  $variables['easy_social_facebook_icon_image'] = array(
    'title' => t("Icono Facebook"),
    'default' => '', // define your variable's default value here
    'group' => 'easy_social',
    'token' => FALSE,
  );

  $variables['easy_social_facebook_icon_account'] = array(
    'title' => t("Cuenta Facebook"),
    'default' => '',
    'group' => 'easy_social',
    'token' => FALSE,
  );

  $variables['easy_social_facebook_icon_target'] = array(
    'title' => t("Target"),
    'type' => 'select',
    'options' => array(
       '_self' => '_self',
       '_blank' => '_blank',
       '_parent' => '_parent',
       '_top' => '_top',
    ),
    'default' => '',
    'group' => 'easy_social',
    'token' => FALSE,
  );

  $variables['easy_social_twitter_icon_image'] = array(
    'title' => t("Icono twitter"),
    'default' => '', // define your variable's default value here
    'group' => 'easy_social',
    'token' => FALSE,
  );

  $variables['easy_social_twitter_icon_account'] = array(
    'title' => t("Cuenta twitter"),
    'default' => '',
    'group' => 'easy_social',
    'token' => FALSE,
  );

  $variables['easy_social_twitter_icon_target'] = array(
    'title' => t("Target"),
    'type' => 'select',
    'options' => array(
       '_self' => '_self',
       '_blank' => '_blank',
       '_parent' => '_parent',
       '_top' => '_top',
    ),
    'default' => '',
    'group' => 'easy_social',
    'token' => FALSE,
  );

  $variables['easy_social_youtube_icon_image'] = array(
    'title' => t("Icono youtube"),
    'default' => '', // define your variable's default value here
    'group' => 'easy_social',
    'token' => FALSE,
  );

  $variables['easy_social_youtube_icon_account'] = array(
    'title' => t("Cuenta youtube"),
    'default' => '',
    'group' => 'easy_social',
    'token' => FALSE,
  );

  $variables['easy_social_youtube_icon_target'] = array(
    'title' => t("Target"),
    'type' => 'select',
    'options' => array(
       '_self' => '_self',
       '_blank' => '_blank',
       '_parent' => '_parent',
       '_top' => '_top',
    ),
    'default' => '',
    'group' => 'easy_social',
    'token' => FALSE,
  );

  $variables['easy_social_instagram_icon_image'] = array(
    'title' => t("Icono instagram"),
    'default' => '', // define your variable's default value here
    'group' => 'easy_social',
    'token' => FALSE,
  );

  $variables['easy_social_instagram_icon_account'] = array(
    'title' => t("Cuenta instagram"),
    'default' => '',
    'group' => 'easy_social',
    'token' => FALSE,
  );

  $variables['easy_social_instagram_icon_target'] = array(
    'title' => t("Target"),
    'type' => 'select',
    'options' => array(
       '_self' => '_self',
       '_blank' => '_blank',
       '_parent' => '_parent',
       '_top' => '_top',
    ),
    'default' => '',
    'group' => 'easy_social',
    'token' => FALSE,
  );

  $variables['easy_social_facebook_counter_image'] = array(
      'title' => t('Icono Facebook Like'),
      'default' => '',
      'group' => 'easy_social',
      'token' => FALSE,
  );

  return $variables;
}

?>